"""根据 install_prefix 生成 mailbus-core/.env。"""

from __future__ import annotations

import os
from pathlib import Path

from paths import MAILBUS_CORE, load_manifest, to_wsl_path


def write_env(
    install_prefix: Path,
    *,
    mailbus_root: Path | None = None,
    mailbus_data: Path | None = None,
    dry_run: bool = False,
) -> Path:
    prefix = install_prefix.resolve()
    root = (mailbus_root or prefix / "mailbus-core").resolve()
    data = (mailbus_data or prefix / "mail" / "store").resolve()

    lines = [
        "# Generated by mailbus migrate — edit paths for your machine",
        f"MAILBUS_ROOT={to_wsl_path(root)}",
        f"MAILBUS_DATA={to_wsl_path(data)}",
        "MAILBUS_API_PORT=9814",
        "COMPOSE_PROJECT_NAME=docker-agents",
        "",
    ]

    manifest = load_manifest()
    for item in manifest.get("infra") or []:
        env = item["env"]
        p = prefix / item["path"]
        if p.exists() or not item.get("optional"):
            lines.append(f"{env}={to_wsl_path(p)}")

    for item in manifest.get("framework_workspaces") or []:
        env = item["env"]
        p = prefix / item.get("default_subpath", item["agent_id"])
        if p.exists():
            lines.append(f"{env}={to_wsl_path(p)}")

    # sensible defaults when sibling dirs exist
    defaults = {
        "OPENCLAW_WORKSPACE": prefix / "openclaw_space",
        "OPENCODE_ROOT": prefix / "opencode",
        "NODE_MODULES": prefix / "node_modules",
        "HERMES_DATA": prefix / "hermes-data" / ".hermes",
        "TEAM_PACK_ROOT": prefix / "team-pack",
    }
    existing_keys = {ln.split("=", 1)[0] for ln in lines if "=" in ln and not ln.startswith("#")}
    for env, p in defaults.items():
        if env not in existing_keys and p.exists():
            lines.append(f"{env}={to_wsl_path(p)}")

    content = "\n".join(lines) + "\n"
    target = root / ".env"
    if dry_run:
        print(content)
        return target
    target.write_text(content, encoding="utf-8")
    return target


def main() -> int:
    import argparse

    ap = argparse.ArgumentParser(description="Write mailbus-core/.env for new install prefix")
    ap.add_argument("--prefix", required=True, help="Install root, e.g. /opt/mailbus or <LOCAL_ROOT>")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()
    write_env(Path(args.prefix), dry_run=args.dry_run)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
