"""根据 install_prefix 生成 mailbus/.env。"""

from __future__ import annotations

from pathlib import Path

from paths import MAILBUS_CORE, load_manifest, to_wsl_path


def write_env(
    install_prefix: Path,
    *,
    mailbus_root: Path | None = None,
    mailbus_data: Path | None = None,
    dry_run: bool = False,
) -> Path:
    prefix = install_prefix.resolve()
    # Prefer in-tree mailbus checkout (this repo); legacy mailbus-core name still accepted.
    if mailbus_root is not None:
        root = mailbus_root.resolve()
    elif (prefix / "mailbus").is_dir():
        root = (prefix / "mailbus").resolve()
    elif (prefix / "mailbus-core").is_dir():
        root = (prefix / "mailbus-core").resolve()
    elif prefix.resolve() == MAILBUS_CORE.resolve() or (prefix / "lib").is_dir():
        root = prefix.resolve()
    else:
        root = (prefix / "mailbus").resolve()
    data = (mailbus_data or root / "store").resolve()

    lines = [
        "# Generated by mailbus migrate — edit paths for your machine",
        f"MAILBUS_ROOT={to_wsl_path(root)}",
        f"MAILBUS_DATA={to_wsl_path(data)}",
        "MAILBUS_API_PORT=9814",
        "COMPOSE_PROJECT_NAME=docker-agents",
        "",
    ]

    manifest = load_manifest()
    existing_keys = {"MAILBUS_ROOT", "MAILBUS_DATA", "MAILBUS_API_PORT", "COMPOSE_PROJECT_NAME"}

    for item in manifest.get("infra") or []:
        env = item["env"]
        p = prefix / item["path"]
        if env in existing_keys:
            continue
        if p.exists() or not item.get("optional"):
            lines.append(f"{env}={to_wsl_path(p)}")
            existing_keys.add(env)

    for item in manifest.get("framework_workspaces") or []:
        env = item["env"]
        sub = item.get("path") or item.get("default_subpath") or item.get("agent_id")
        if not sub or env in existing_keys:
            continue
        p = prefix / sub
        if p.exists():
            lines.append(f"{env}={to_wsl_path(p)}")
            existing_keys.add(env)

    content = "\n".join(lines) + "\n"
    target = root / ".env"
    if dry_run:
        print(content)
        return target
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    return target


def main() -> int:
    import argparse

    ap = argparse.ArgumentParser(description="Write mailbus/.env for new install prefix")
    ap.add_argument("--prefix", required=True, help="Install root, e.g. /opt/mailbus or <LOCAL_ROOT>")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()
    write_env(Path(args.prefix), dry_run=args.dry_run)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
