"""Framework adapters — Strategy registry (Wave1-B)."""
from lib.adapters.frameworks.registry import (  # noqa: F401
    ADAPTERS,
    A2ARemoteAdapter,
    BaseAdapter,
    ClaudeCodeAdapter,
    ClineAdapter,
    CodexAdapter,
    CursorAdapter,
    HermesAdapter,
    HermesProfileAdapter,
    NoneAdapter,
    OpenClawAdapter,
    OpenCodeAdapter,
    _flag_value,
    _push_cwd,
    agent_cli_active,
    agent_cli_active_for,
    container_for_service,
    container_prefix,
    framework_adapter_spec,
    get_adapter,
    list_frameworks,
    model_flag,
    provider_flag,
    push_timeout_for,
    register_framework,
    resolve_container,
    resolve_interactive_cli,
    resolve_push_cli,
    should_mark_processing_on_push,
    shlex_quote,
    store_path_for_agent,
    type_supports_auto_ack,
    unregister_framework,
    validate_agents,
)

try:
    from lib.adapters.frameworks.entry_point_discovery import (  # noqa: F401
        discover_and_register_frameworks,
        ensure_framework_plugins_loaded,
    )
except Exception:  # pragma: no cover
    discover_and_register_frameworks = None  # type: ignore[assignment]
    ensure_framework_plugins_loaded = None  # type: ignore[assignment]

__all__ = [
    "ADAPTERS",
    "A2ARemoteAdapter",
    "BaseAdapter",
    "ClaudeCodeAdapter",
    "ClineAdapter",
    "CodexAdapter",
    "CursorAdapter",
    "HermesAdapter",
    "HermesProfileAdapter",
    "NoneAdapter",
    "OpenClawAdapter",
    "OpenCodeAdapter",
    "_flag_value",
    "_push_cwd",
    "agent_cli_active",
    "agent_cli_active_for",
    "container_for_service",
    "container_prefix",
    "framework_adapter_spec",
    "get_adapter",
    "list_frameworks",
    "model_flag",
    "provider_flag",
    "push_timeout_for",
    "register_framework",
    "discover_and_register_frameworks",
    "ensure_framework_plugins_loaded",
    "resolve_container",
    "resolve_interactive_cli",
    "resolve_push_cli",
    "should_mark_processing_on_push",
    "shlex_quote",
    "store_path_for_agent",
    "type_supports_auto_ack",
    "unregister_framework",
    "validate_agents",
]
