#!/usr/bin/env python3
"""Generate docker-compose volume mounts from access/**/agent.json (Phase 3.3).

Usage:
  python tools/generate-compose-volumes.py
  python tools/generate-compose-volumes.py --check   # exit 2 if compose drift
  python tools/generate-compose-volumes.py --host-prefix /mnt/e
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from lib.agent_registry import load_all_agents  # noqa: E402
from lib.constants import MAILBUS_ROOT  # noqa: E402
from lib.sync_layers import normalize_host_path  # noqa: E402

COMPOSE_PATH = ROOT / "docker-agents" / "docker-compose.yml"

# Legacy mounts removed in Phase 3.3 (#17 #27 #34)
FORBIDDEN_PATTERNS = (
    re.compile(r"/mailbus/adapters"),
    re.compile(r"/mailbus/roles"),
    re.compile(r"/mailbus/identities"),
    re.compile(r"mail/external-tools:"),
    re.compile(r"adapters/\.sync"),
)

# Required on agent-facing services (hermes, openclaw, codex*, dali, mailbus)
REQUIRED_AGENT_MOUNTS = (
    "/mailbus/skills",
    "/mailbus/access",
    "/mailbus/rules",
)

MAILBUS_SERVICE_MOUNTS = (
    "/mailbus/skills",
    "/mailbus/access",
    "/mailbus/rules",
)

HERMES_EXTRA = ("/mailbus/access/hermes/.sync",)


def _host_prefix(arg: str, mail_root: Path) -> str:
    if arg:
        return arg.rstrip("/")
    # WSL default when mail lives on E:
    drive = mail_root.drive.rstrip(":").lower() if mail_root.drive else "e"
    return f"/mnt/{drive}"


def _to_compose_host(path: Path, host_prefix: str) -> str:
    """Native Path → /mnt/e/... for compose."""
    s = str(path.resolve()).replace("\\", "/")
    if s.startswith("/mnt/"):
        return s
    m = re.match(r"^([A-Za-z]):/(.*)$", s)
    if m:
        return f"{host_prefix}/{m.group(2)}"
    return s


def standard_mail_mounts(host_prefix: str, *, mail_root: Path | None = None) -> list[str]:
    root = mail_root or MAILBUS_ROOT
    hp = _to_compose_host(root, host_prefix)
    lines = [
        f"      - {hp}:/mailbus",
        f"      - {hp}/skills:/mailbus/skills:ro",
        f"      - {hp}/rules:/mailbus/rules:ro",
        f"      - {hp}/access:/mailbus/access:ro",
        f"      - {hp}/access/external-tools:/mailbus/external-tools:ro",
    ]
    return lines


def hermes_service_mounts(host_prefix: str, *, mail_root: Path | None = None) -> list[str]:
    root = mail_root or MAILBUS_ROOT
    hp = _to_compose_host(root, host_prefix)
    lines = [
        f"      - {hp}/store:/mailbus/store",
        f"      - {hp}/tools:/mailbus/tools:ro",
        f"      - {hp}/skills:/mailbus/skills:ro",
        f"      - {hp}/rules:/mailbus/rules:ro",
        f"      - {hp}/access:/mailbus/access:ro",
        f"      - {hp}/access/external-tools:/mailbus/external-tools:ro",
        f"      - {hp}/access/hermes/.sync:/mailbus/access/hermes/.sync",
    ]
    return lines


def workspace_mounts(host_prefix: str, *, mail_root: Path | None = None) -> dict[str, list[str]]:
    """Per docker service name → extra workspace volume lines."""
    root = mail_root or MAILBUS_ROOT
    out: dict[str, list[str]] = {}
    for agent_id, rec in sorted(load_all_agents(mail_root=root, refresh=True).items()):
        docker = rec.get("docker") or {}
        service = (docker.get("service") or "").strip()
        ws = rec.get("workspace")
        if not service or not ws:
            continue
        fw = rec.get("framework") or ""
        host_path = normalize_host_path(str(ws), mail_root=root)
        hp = _to_compose_host(host_path, host_prefix)
        lines = out.setdefault(service, [])
        if fw == "opencode":
            lines.append(f"      - {hp}:/workspace/opencode:ro")
            skills_hp = _to_compose_host(host_path / "skills", host_prefix)
            lines.append(f"      - {skills_hp}:/workspace/opencode/skills")
        elif fw == "openclaw":
            lines.append(f"      - {hp}:/workspace")
        elif fw == "codex":
            lines.append(f"      - {hp}:/workspace/{agent_id}:ro")
        elif fw == "claude_code":
            claude_hp = _to_compose_host(host_path, host_prefix)
            lines.append(f"      - {claude_hp}:/{agent_id}-workspace:ro")
    return out


def render_fragment(host_prefix: str) -> str:
    parts = ["# --- generated by tools/generate-compose-volumes.py ---", ""]
    parts.append("# mailbus service volumes:")
    parts.extend(standard_mail_mounts(host_prefix))
    parts.append("")
    parts.append("# hermes service volumes:")
    parts.extend(hermes_service_mounts(host_prefix))
    parts.append("")
    parts.append("# workspace mounts by docker service:")
    for svc, lines in workspace_mounts(host_prefix).items():
        parts.append(f"# {svc}:")
        parts.extend(lines)
    parts.append("# --- end generated fragment ---")
    return "\n".join(parts) + "\n"


def check_compose(compose_text: str) -> list[str]:
    errors: list[str] = []
    for pat in FORBIDDEN_PATTERNS:
        if pat.search(compose_text):
            errors.append(f"forbidden mount pattern still present: {pat.pattern}")
    for req in REQUIRED_AGENT_MOUNTS:
        if req not in compose_text:
            errors.append(f"missing required mount target: {req}")
    if "/mailbus/access/hermes/.sync" not in compose_text:
        errors.append("missing hermes .sync mount: /mailbus/access/hermes/.sync")
    if "/mailbus/external-tools" not in compose_text:
        errors.append("missing external-tools mount: /mailbus/external-tools")
    return errors


def main() -> int:
    p = argparse.ArgumentParser(description="Generate/check docker-compose volume mounts")
    p.add_argument("--host-prefix", default="", help="WSL host prefix, default /mnt/{drive}")
    p.add_argument("--check", action="store_true", help="Verify docker-compose.yml has v3 mounts")
    p.add_argument("--print", action="store_true", help="Print generated fragment to stdout")
    args = p.parse_args()

    hp = _host_prefix(args.host_prefix, MAILBUS_ROOT)

    if args.print or not args.check:
        print(render_fragment(hp))

    if args.check:
        if not COMPOSE_PATH.is_file():
            print(f"ERROR: missing {COMPOSE_PATH}", file=sys.stderr)
            return 1
        text = COMPOSE_PATH.read_text(encoding="utf-8")
        errors = check_compose(text)
        if errors:
            for e in errors:
                print("FAIL", e, file=sys.stderr)
            return 2
        print("OK: docker-compose.yml v3 mounts")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
